from dataclasses import dataclass


@dataclass(frozen=True)
class SecurityDefinition:
    ticker: str
    name: str
    sector: str


DEFAULT_UNIVERSE = [
    SecurityDefinition("AAPL", "Apple Inc.", "Information Technology"),
    SecurityDefinition("MSFT", "Microsoft Corp.", "Information Technology"),
    SecurityDefinition("NVDA", "NVIDIA Corp.", "Information Technology"),
    SecurityDefinition("AMZN", "Amazon.com Inc.", "Consumer Discretionary"),
    SecurityDefinition("META", "Meta Platforms Inc.", "Communication Services"),
    SecurityDefinition("GOOGL", "Alphabet Inc.", "Communication Services"),
    SecurityDefinition("BRK.B", "Berkshire Hathaway Inc.", "Financials"),
    SecurityDefinition("JPM", "JPMorgan Chase & Co.", "Financials"),
    SecurityDefinition("UNH", "UnitedHealth Group Inc.", "Health Care"),
    SecurityDefinition("LLY", "Eli Lilly and Co.", "Health Care"),
    SecurityDefinition("XOM", "Exxon Mobil Corp.", "Energy"),
    SecurityDefinition("PG", "Procter & Gamble Co.", "Consumer Staples"),
    SecurityDefinition("COST", "Costco Wholesale Corp.", "Consumer Staples"),
    SecurityDefinition("HD", "Home Depot Inc.", "Consumer Discretionary"),
    SecurityDefinition("AVGO", "Broadcom Inc.", "Information Technology"),
    SecurityDefinition("V", "Visa Inc.", "Financials"),
    SecurityDefinition("MA", "Mastercard Inc.", "Financials"),
    SecurityDefinition("JNJ", "Johnson & Johnson", "Health Care"),
    SecurityDefinition("WMT", "Walmart Inc.", "Consumer Staples"),
    SecurityDefinition("SPY", "SPDR S&P 500 ETF Trust", "Benchmark"),
]

LARGE_CAP_UNIVERSE = [
    SecurityDefinition("AAPL", "Apple Inc.", "Information Technology"),
    SecurityDefinition("MSFT", "Microsoft Corp.", "Information Technology"),
    SecurityDefinition("NVDA", "NVIDIA Corp.", "Information Technology"),
    SecurityDefinition("AMZN", "Amazon.com Inc.", "Consumer Discretionary"),
    SecurityDefinition("META", "Meta Platforms Inc.", "Communication Services"),
    SecurityDefinition("GOOGL", "Alphabet Inc.", "Communication Services"),
    SecurityDefinition("BRK.B", "Berkshire Hathaway Inc.", "Financials"),
    SecurityDefinition("LLY", "Eli Lilly and Co.", "Health Care"),
    SecurityDefinition("AVGO", "Broadcom Inc.", "Information Technology"),
    SecurityDefinition("JPM", "JPMorgan Chase & Co.", "Financials"),
    SecurityDefinition("TSLA", "Tesla Inc.", "Consumer Discretionary"),
    SecurityDefinition("V", "Visa Inc.", "Financials"),
    SecurityDefinition("XOM", "Exxon Mobil Corp.", "Energy"),
    SecurityDefinition("UNH", "UnitedHealth Group Inc.", "Health Care"),
    SecurityDefinition("MA", "Mastercard Inc.", "Financials"),
    SecurityDefinition("COST", "Costco Wholesale Corp.", "Consumer Staples"),
    SecurityDefinition("WMT", "Walmart Inc.", "Consumer Staples"),
    SecurityDefinition("PG", "Procter & Gamble Co.", "Consumer Staples"),
    SecurityDefinition("JNJ", "Johnson & Johnson", "Health Care"),
    SecurityDefinition("HD", "Home Depot Inc.", "Consumer Discretionary"),
    SecurityDefinition("ABBV", "AbbVie Inc.", "Health Care"),
    SecurityDefinition("BAC", "Bank of America Corp.", "Financials"),
    SecurityDefinition("KO", "Coca-Cola Co.", "Consumer Staples"),
    SecurityDefinition("NFLX", "Netflix Inc.", "Communication Services"),
    SecurityDefinition("PM", "Philip Morris International Inc.", "Consumer Staples"),
    SecurityDefinition("CRM", "Salesforce Inc.", "Information Technology"),
    SecurityDefinition("ORCL", "Oracle Corp.", "Information Technology"),
    SecurityDefinition("CVX", "Chevron Corp.", "Energy"),
    SecurityDefinition("CSCO", "Cisco Systems Inc.", "Information Technology"),
    SecurityDefinition("ABT", "Abbott Laboratories", "Health Care"),
    SecurityDefinition("WFC", "Wells Fargo & Co.", "Financials"),
    SecurityDefinition("MCD", "McDonald's Corp.", "Consumer Discretionary"),
    SecurityDefinition("LIN", "Linde plc", "Materials"),
    SecurityDefinition("IBM", "International Business Machines Corp.", "Information Technology"),
    SecurityDefinition("GE", "GE Aerospace", "Industrials"),
    SecurityDefinition("MRK", "Merck & Co. Inc.", "Health Care"),
    SecurityDefinition("TMO", "Thermo Fisher Scientific Inc.", "Health Care"),
    SecurityDefinition("ISRG", "Intuitive Surgical Inc.", "Health Care"),
    SecurityDefinition("NOW", "ServiceNow Inc.", "Information Technology"),
    SecurityDefinition("PEP", "PepsiCo Inc.", "Consumer Staples"),
    SecurityDefinition("ACN", "Accenture plc", "Information Technology"),
    SecurityDefinition("DIS", "Walt Disney Co.", "Communication Services"),
    SecurityDefinition("GS", "Goldman Sachs Group Inc.", "Financials"),
    SecurityDefinition("AMD", "Advanced Micro Devices Inc.", "Information Technology"),
    SecurityDefinition("ADBE", "Adobe Inc.", "Information Technology"),
    SecurityDefinition("QCOM", "Qualcomm Inc.", "Information Technology"),
    SecurityDefinition("TXN", "Texas Instruments Inc.", "Information Technology"),
    SecurityDefinition("CAT", "Caterpillar Inc.", "Industrials"),
    SecurityDefinition("VZ", "Verizon Communications Inc.", "Communication Services"),
    SecurityDefinition("T", "AT&T Inc.", "Communication Services"),
    SecurityDefinition("AMGN", "Amgen Inc.", "Health Care"),
    SecurityDefinition("AXP", "American Express Co.", "Financials"),
    SecurityDefinition("UBER", "Uber Technologies Inc.", "Industrials"),
    SecurityDefinition("BKNG", "Booking Holdings Inc.", "Consumer Discretionary"),
    SecurityDefinition("PFE", "Pfizer Inc.", "Health Care"),
    SecurityDefinition("RTX", "RTX Corp.", "Industrials"),
    SecurityDefinition("SPGI", "S&P Global Inc.", "Financials"),
    SecurityDefinition("MS", "Morgan Stanley", "Financials"),
    SecurityDefinition("LOW", "Lowe's Cos. Inc.", "Consumer Discretionary"),
    SecurityDefinition("BLK", "BlackRock Inc.", "Financials"),
    SecurityDefinition("PGR", "Progressive Corp.", "Financials"),
    SecurityDefinition("NEE", "NextEra Energy Inc.", "Utilities"),
    SecurityDefinition("HON", "Honeywell International Inc.", "Industrials"),
    SecurityDefinition("TJX", "TJX Cos. Inc.", "Consumer Discretionary"),
    SecurityDefinition("SYK", "Stryker Corp.", "Health Care"),
    SecurityDefinition("C", "Citigroup Inc.", "Financials"),
    SecurityDefinition("SCHW", "Charles Schwab Corp.", "Financials"),
    SecurityDefinition("DHR", "Danaher Corp.", "Health Care"),
    SecurityDefinition("UNP", "Union Pacific Corp.", "Industrials"),
    SecurityDefinition("BA", "Boeing Co.", "Industrials"),
    SecurityDefinition("CMCSA", "Comcast Corp.", "Communication Services"),
    SecurityDefinition("AMAT", "Applied Materials Inc.", "Information Technology"),
    SecurityDefinition("COP", "ConocoPhillips", "Energy"),
    SecurityDefinition("DE", "Deere & Co.", "Industrials"),
    SecurityDefinition("GILD", "Gilead Sciences Inc.", "Health Care"),
    SecurityDefinition("ETN", "Eaton Corp. plc", "Industrials"),
    SecurityDefinition("PANW", "Palo Alto Networks Inc.", "Information Technology"),
    SecurityDefinition("ADP", "Automatic Data Processing Inc.", "Industrials"),
    SecurityDefinition("LRCX", "Lam Research Corp.", "Information Technology"),
    SecurityDefinition("BSX", "Boston Scientific Corp.", "Health Care"),
    SecurityDefinition("ADI", "Analog Devices Inc.", "Information Technology"),
    SecurityDefinition("VRTX", "Vertex Pharmaceuticals Inc.", "Health Care"),
    SecurityDefinition("MDT", "Medtronic plc", "Health Care"),
    SecurityDefinition("CB", "Chubb Ltd.", "Financials"),
    SecurityDefinition("MMC", "Marsh & McLennan Cos. Inc.", "Financials"),
    SecurityDefinition("PLD", "Prologis Inc.", "Real Estate"),
    SecurityDefinition("SBUX", "Starbucks Corp.", "Consumer Discretionary"),
    SecurityDefinition("BMY", "Bristol Myers Squibb Co.", "Health Care"),
    SecurityDefinition("MU", "Micron Technology Inc.", "Information Technology"),
    SecurityDefinition("SO", "Southern Co.", "Utilities"),
    SecurityDefinition("MO", "Altria Group Inc.", "Consumer Staples"),
    SecurityDefinition("KLAC", "KLA Corp.", "Information Technology"),
    SecurityDefinition("DUK", "Duke Energy Corp.", "Utilities"),
    SecurityDefinition("ICE", "Intercontinental Exchange Inc.", "Financials"),
    SecurityDefinition("NKE", "Nike Inc.", "Consumer Discretionary"),
    SecurityDefinition("LMT", "Lockheed Martin Corp.", "Industrials"),
    SecurityDefinition("INTC", "Intel Corp.", "Information Technology"),
    SecurityDefinition("MDLZ", "Mondelez International Inc.", "Consumer Staples"),
    SecurityDefinition("ELV", "Elevance Health Inc.", "Health Care"),
    SecurityDefinition("AON", "Aon plc", "Financials"),
    SecurityDefinition("SPY", "SPDR S&P 500 ETF Trust", "Benchmark"),
]


def load_default_universe(limit: int | None = None) -> list[SecurityDefinition]:
    universe = DEFAULT_UNIVERSE if limit is None else DEFAULT_UNIVERSE[:limit]
    return list(universe)


def load_large_cap_universe(limit: int | None = None) -> list[SecurityDefinition]:
    if limit is None:
        return list(LARGE_CAP_UNIVERSE)

    benchmark = [security for security in LARGE_CAP_UNIVERSE if security.ticker == "SPY"]
    stocks = [security for security in LARGE_CAP_UNIVERSE if security.ticker != "SPY"]
    return stocks[:limit] + benchmark
